# Generated by Django 5.2.3 on 2025-06-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, help_text='A brief summary of the post, used for previews (e.g., on index pages, social media, Telegram).'),
        ),
    ]
