# Generated by Django 5.2.3 on 2025-06-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='download_section_title',
            field=models.CharField(blank=True, default='Download Links', max_length=100),
        ),
    ]
