# Generated by Django 4.2.13 on 2025-06-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_download_section_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='enable_downloads',
            field=models.BooleanField(default=True, help_text='Show download section for this post'),
        ),
    ]
