# Generated by Django 4.2.13 on 2025-07-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_views_alter_post_enable_downloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadquality',
            name='quality',
            field=models.CharField(choices=[('360p', 'DOWNLOAD [360p]'), ('480p', 'DOWNLOAD [480p]'), ('720p', 'DOWNLOAD [720p (HD)]'), ('1080p', 'DOWNLOAD [1080p (FHD)]'), ('4K', 'DOWNLOAD [4K (UHD)]')], max_length=10),
        ),
    ]
