# Generated by Django 4.2.13 on 2025-07-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_downloadquality_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='seo_title',
            field=models.CharField(blank=True, help_text="(e.g., 'Henry Danger S1 EP20 - Series Download'). If left blank, the main title will be used.", max_length=255, null=True),
        ),
    ]
