# Generated by Django 4.2.13 on 2025-07-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_downloadquality_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadquality',
            name='quality',
            field=models.CharField(choices=[('360p', 'DOWNLOAD MOVIE [360p]'), ('480p', 'DOWNLOAD MOVIE [480p]'), ('720p', 'DOWNLOAD MOVIE [720p (HD)]'), ('1080p', 'DOWNLOAD MOVIE 1080p (FHD)]'), ('4K', 'DOWNLOAD [4K (UHD)]'), ('EP1', 'DOWNLOAD EPISODE 1'), ('EP2', 'DOWNLOAD EPISODE 2'), ('EP3', 'DOWNLOAD EPISODE 3'), ('EP4', 'DOWNLOAD EPISODE 4'), ('EP5', 'DOWNLOAD EPISODE 5'), ('EP6', 'DOWNLOAD EPISODE 6'), ('EP7', 'DOWNLOAD EPISODE 7'), ('EP8', 'DOWNLOAD EPISODE 8'), ('EP9', 'DOWNLOAD EPISODE 9'), ('EP10', 'DOWNLOAD EPISODE 10'), ('EP11', 'DOWNLOAD EPISODE 11'), ('EP12', 'DOWNLOAD EPISODE 12'), ('EP13', 'DOWNLOAD EPISODE 13'), ('EP14', 'DOWNLOAD EPISODE 14'), ('EP15', 'DOWNLOAD EPISODE 15'), ('EP16', 'DOWNLOAD EPISODE 16'), ('EP17', 'DOWNLOAD EPISODE 17'), ('EP18', 'DOWNLOAD EPISODE 18'), ('EP19', 'DOWNLOAD EPISODE 19'), ('EP20', 'DOWNLOAD EPISODE 20'), ('EP21', 'DOWNLOAD EPISODE 21'), ('EP22', 'DOWNLOAD EPISODE 22'), ('EP23', 'DOWNLOAD EPISODE 23'), ('EP24', 'DOWNLOAD EPISODE 24'), ('EP25', 'DOWNLOAD EPISODE 25'), ('EP26', 'DOWNLOAD EPISODE 26'), ('EP27', 'DOWNLOAD EPISODE 27'), ('EP28', 'DOWNLOAD EPISODE 28'), ('EP29', 'DOWNLOAD EPISODE 29'), ('EP30', 'DOWNLOAD EPISODE 30'), ('EP31', 'DOWNLOAD EPISODE 31'), ('EP32', 'DOWNLOAD EPISODE 32'), ('EP33', 'DOWNLOAD EPISODE 33'), ('EP34', 'DOWNLOAD EPISODE 34'), ('EP35', 'DOWNLOAD EPISODE 35'), ('EP36', 'DOWNLOAD EPISODE 36'), ('EP37', 'DOWNLOAD EPISODE 37'), ('EP38', 'DOWNLOAD EPISODE 38'), ('EP39', 'DOWNLOAD EPISODE 39'), ('EP40', 'DOWNLOAD EPISODE 40')], max_length=10),
        ),
    ]
