# Generated by Django 4.2.13 on 2025-07-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A human-readable name for the ad (e.g., 'Homepage Banner', 'Sidebar Ad').", max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text="A unique identifier for the ad, used to reference it in templates (e.g., 'homepage-banner').", max_length=255, unique=True)),
                ('ad_content', models.TextField(help_text='The full HTML or JavaScript code for the advertisement.')),
                ('is_active', models.BooleanField(default=True, help_text='Check to display this ad on the website. Uncheck to temporarily hide it.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the ad was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the ad was last updated.')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['name'],
            },
        ),
    ]
