# Generated by Django 4.2.13 on 2025-07-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['name'], 'verbose_name': 'Advertisement', 'verbose_name_plural': 'Advertisements'},
        ),
        migrations.RemoveField(
            model_name='ad',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='code',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='placement',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='target_url',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='views',
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_content',
            field=models.TextField(default=1, help_text='The full HTML or JavaScript code for the advertisement.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='slug',
            field=models.SlugField(blank=True, help_text="A unique identifier for the ad, used to reference it in templates (e.g., 'homepage-banner').", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the ad was created.'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Check to display this ad on the website. Uncheck to temporarily hide it.'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.CharField(help_text="A human-readable name for the ad (e.g., 'Homepage Banner', 'Sidebar Ad').", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when the ad was last updated.'),
        ),
        migrations.DeleteModel(
            name='AdPlacement',
        ),
    ]
